import type { EmissionProfile } from '@vtex-email/core'

const comparisonOperators = ['==', '===', '!=', '<', '<=', '>', '>='] as const

export const messageCenterEmission: EmissionProfile = {
  id: 'p0-message-center-experimental',
  allowParentSegments: true,
  capabilities: [
    {
      name: 'each',
      form: 'block',
      evidence: 'documented',
      note: 'Native Handlebars helper. The item context replaces the current context. The fallback uses the outer context.',
      context: 'item',
      elseContext: 'outer',
    },
    {
      name: 'if',
      form: 'block',
      evidence: 'documented',
      note: 'Handlebars truthiness. 0, an empty string, and an empty array are false. The toolchain does not use Boolean(). Both branches keep the current context.',
      context: 'preserve',
      elseContext: 'preserve',
    },
    {
      name: 'unless',
      form: 'block',
      evidence: 'documented',
      note: 'Negation of if. Both branches keep the current context.',
      context: 'preserve',
      elseContext: 'preserve',
    },
    {
      name: '../',
      form: 'path',
      evidence: 'documented',
      note: 'Parent segment documented by Handlebars. A path cannot climb above the template root.',
    },
    {
      name: '@index',
      form: 'path',
      evidence: 'experimental',
      note: 'Zero-based index inside each. Not available in group. Not verified on Message Center.',
    },
    {
      name: 'formatCurrency',
      form: 'inline',
      evidence: 'documented',
      note: 'VTEX documents 20000 as 200,00, without a symbol. Other integers follow the same local simulator, without verified parity.',
      arity: { min: 1, max: 1 },
      args: ['path'],
    },
    {
      name: 'formatDate',
      form: 'inline',
      evidence: 'experimental',
      note: 'Local dd/MM/yyyy from a Date-parseable path. Timezone follows the host Date. Not verified on Message Center.',
      arity: { min: 1, max: 1 },
      args: ['path'],
    },
    {
      name: 'formatTime',
      form: 'inline',
      evidence: 'experimental',
      note: 'Local HH:mm from a Date-parseable path. Zero-padded 24-hour clock. Timezone follows the host Date. Not verified on Message Center.',
      arity: { min: 1, max: 1 },
      args: ['path'],
    },
    {
      name: 'formatDateTime',
      form: 'inline',
      evidence: 'experimental',
      note: 'Local dd/MM/yyyy HH:mm:ss from a Date-parseable path. Zero-padded 24-hour clock. Timezone follows the host Date. Not verified on Message Center.',
      arity: { min: 1, max: 1 },
      args: ['path'],
    },
    {
      name: 'replace',
      form: 'inline',
      evidence: 'documented',
      note: 'Replaces the first occurrence. Search and replacement are path or literal. The simulator expects three strings.',
      arity: { min: 3, max: 3 },
      args: ['path', 'expression', 'expression'],
    },
    {
      name: 'eq',
      form: 'block',
      evidence: 'experimental',
      note: 'Strict equality. Path versus path or path versus literal. Both branches keep context. Not verified on Message Center.',
      arity: { min: 1, max: 1 },
      args: ['expression'],
      context: 'preserve',
      elseContext: 'preserve',
    },
    {
      name: 'ifCond',
      form: 'block',
      evidence: 'experimental',
      note: 'Compares a path to a path or literal with ==, ===, !=, <, <=, >, or >=. Unknown operators fail at compile time. Both branches keep context. Project-local helper; not verified on Message Center.',
      arity: { min: 2, max: 2 },
      args: ['literal', 'expression'],
      literals: [{ index: 0, values: comparisonOperators }],
      context: 'preserve',
      elseContext: 'preserve',
    },
    {
      name: 'hasSubStr',
      form: 'block',
      evidence: 'experimental',
      note: 'True when the path value is not null and String(value) contains the search path or literal. Both branches keep context. Project-local helper; not verified on Message Center.',
      arity: { min: 1, max: 1 },
      args: ['expression'],
      context: 'preserve',
      elseContext: 'preserve',
    },
    {
      name: 'group',
      form: 'block',
      evidence: 'experimental',
      note: 'Groups an array by a hash by identifier. The item context is { index, value, items }. Empty or missing lists use the outer fallback. Does not invent keys. Project-local helper; not verified on Message Center.',
      hash: [{ name: 'by', kind: 'literal' }],
      context: 'item',
      elseContext: 'outer',
    },
    {
      name: 'with',
      form: 'block',
      evidence: 'experimental',
      note: 'Native Handlebars with. The object becomes the current context. The fallback uses the outer context. Not verified on Message Center.',
      context: 'item',
      elseContext: 'outer',
    },
    {
      name: 'math',
      form: 'inline',
      evidence: 'experimental',
      note: 'Arithmetic on two expressions with +, -, *, /, or %. Non-finite results fail the local simulator. Not verified on Message Center.',
      arity: { min: 3, max: 3 },
      args: ['expression', 'literal', 'expression'],
      literals: [{ index: 1, values: ['+', '-', '*', '/', '%'] }],
    },
    {
      name: 'math',
      form: 'block',
      evidence: 'experimental',
      note: 'Block form of math used by official templates. Path is the left operand; args are the operator and the right expression. Does not push context. Not verified on Message Center.',
      arity: { min: 2, max: 2 },
      args: ['literal', 'expression'],
      literals: [{ index: 0, values: ['+', '-', '*', '/', '%'] }],
      context: 'preserve',
      elseContext: 'preserve',
    },
    {
      name: 'richShippingData',
      form: 'block',
      evidence: 'experimental',
      note: 'Clones shippingData, selects the SLA matching selectedSla, derives packageId and estimate fields on logisticsInfo, then renders with shippingData as the current context. Does not mutate the fixture. Not verified on Message Center.',
      context: 'item',
      elseContext: 'outer',
    },
  ],
}
